apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: train-model-deployment

spec:
  replicas: 1
  # maxReplicas: 4
  # minReplicas: 2
  selector:
    matchLabels:
        app: train-model-deployment
  template:
    metadata:
      labels: 
        app: train-model-deployment
    spec:
      containers:
      - name: train-model-deployment
        image: zpozdniakov/train-model:local
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000

        resources:
          requests:
            memory: 5Mi

        livenessProbe:
          httpGet:
            path: /livetest
            port: 5000
            httpHeaders:
            - name: Custom-Header
              value: Awesome
          initialDelaySeconds: 5
          periodSeconds: 3

        readinessProbe:
          httpGet:
            path: /readiness
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 3
