apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: train-model-replicaset

spec:
  replicas: 1
  selector:
    matchLabels:
        app: train-model-replicaset
  template:
    metadata:
      labels: 
        app: train-model-replicaset
    spec:
      containers:
      - name: train-model-replicaset
        image: zpozdniakov/train-model:local
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000

        livenessProbe:
          httpGet:
            path: /livetest
            port: 5000
            httpHeaders:
            - name: Custom-Header
              value: Awesome
          initialDelaySeconds: 5
          periodSeconds: 3

        readinessProbe:
          httpGet:
            path: /readiness
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 3
