apiVersion: v1
kind: Service
metadata:
  name: train-model-app
spec:
  type: NodePort
  ports:
  - protocol: TCP
    nodePort: 30036
    port: 9090
    targetPort: 5000
  selector:
    app: train-model-replicaset