{
  "kind": "Deployment",
  "apiVersion": "extensions/v1beta1",
  "metadata": {
    "name": "model-train-app",
    "namespace": "default",
    "selfLink": "/apis/extensions/v1beta1/namespaces/default/deployments/model-train-app",
    "uid": "79261030-4cb5-11e9-987a-8abd5e058187",
    "resourceVersion": "40235",
    "generation": 2,
    "creationTimestamp": "2019-03-22T15:16:31Z",
    "labels": {
      "run": "model-train-app"
    },
    "annotations": {
      "deployment.kubernetes.io/revision": "1",
      "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"extensions/v1beta1\",\"kind\":\"Deployment\",\"metadata\":{\"annotations\":{\"deployment.kubernetes.io/revision\":\"1\"},\"creationTimestamp\":\"2019-03-22T15:16:31Z\",\"generation\":1,\"labels\":{\"run\":\"model-train-app\"},\"name\":\"model-train-app\",\"namespace\":\"default\",\"resourceVersion\":\"38916\",\"selfLink\":\"/apis/extensions/v1beta1/namespaces/default/deployments/model-train-app\",\"uid\":\"79261030-4cb5-11e9-987a-8abd5e058187\"},\"spec\":{\"progressDeadlineSeconds\":2147483647,\"replicas\":1,\"revisionHistoryLimit\":2147483647,\"selector\":{\"matchLabels\":{\"run\":\"model-train-app\"}},\"strategy\":{\"rollingUpdate\":{\"maxSurge\":1,\"maxUnavailable\":1},\"type\":\"RollingUpdate\"},\"template\":{\"metadata\":{\"creationTimestamp\":null,\"labels\":{\"run\":\"model-train-app\"}},\"spec\":{\"containers\":[{\"image\":\"zpozdniakov/train-model:v1\",\"imagePullPolicy\":\"IfNotPresent\",\"name\":\"model-train-app\",\"ports\":[{\"containerPort\":5000,\"protocol\":\"TCP\"}],\"resources\":{},\"terminationMessagePath\":\"/dev/termination-log\",\"terminationMessagePolicy\":\"File\"}],\"dnsPolicy\":\"ClusterFirst\",\"restartPolicy\":\"Always\",\"schedulerName\":\"default-scheduler\",\"securityContext\":{},\"terminationGracePeriodSeconds\":30}}},\"status\":{\"availableReplicas\":1,\"conditions\":[{\"lastTransitionTime\":\"2019-03-22T15:16:31Z\",\"lastUpdateTime\":\"2019-03-22T15:16:31Z\",\"message\":\"Deployment has minimum availability.\",\"reason\":\"MinimumReplicasAvailable\",\"status\":\"True\",\"type\":\"Available\"}],\"observedGeneration\":1,\"readyReplicas\":1,\"replicas\":1,\"updatedReplicas\":1}}\n"
    }
  },
  "spec": {
    "replicas": 1,
    "selector": {
      "matchLabels": {
        "run": "model-train-app"
      }
    },
    "template": {
      "metadata": {
        "creationTimestamp": null,
        "labels": {
          "run": "model-train-app"
        }
      },
      "spec": {
        "containers": [
          {
            "name": "model-train-app",
            "image": "zpozdniakov/train-model:v1",
            "ports": [
              {
                "containerPort": 5000,
                "protocol": "TCP"
              }
            ],
            "resources": {},
            "terminationMessagePath": "/dev/termination-log",
            "terminationMessagePolicy": "File",
            "imagePullPolicy": "IfNotPresent"
          }
        ],
        "restartPolicy": "Always",
        "terminationGracePeriodSeconds": 30,
        "dnsPolicy": "ClusterFirst",
        "securityContext": {},
        "schedulerName": "default-scheduler"
      }
    },
    "strategy": {
      "type": "RollingUpdate",
      "rollingUpdate": {
        "maxUnavailable": 1,
        "maxSurge": 1
      }
    },
    "revisionHistoryLimit": 2147483647,
    "progressDeadlineSeconds": 2147483647
  },
  "status": {
    "observedGeneration": 2,
    "replicas": 1,
    "updatedReplicas": 1,
    "readyReplicas": 1,
    "availableReplicas": 1,
    "conditions": [
      {
        "type": "Available",
        "status": "True",
        "lastUpdateTime": "2019-03-22T15:16:31Z",
        "lastTransitionTime": "2019-03-22T15:16:31Z",
        "reason": "MinimumReplicasAvailable",
        "message": "Deployment has minimum availability."
      }
    ]
  }
}